// Code generated by Slice Machine. DO NOT EDIT.
import dynamic from 'next/dynamic';

export const components = {
	all_services: dynamic(() => import('./ServiceItem')),
	contact_info: dynamic(() => import('./ContactInfo')),
	start_screen: dynamic(() => import('./StartScreen')),
};
