// Code generated by Slice Machine. DO NOT EDIT.
import type * as prismic from '@prismicio/client';

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type ContactPageDocumentDataSlicesSlice = ContactInfoSlice;

/**
 * Content for Contact Page documents
 */
interface ContactPageDocumentData {
	/**
	 * title main field in *Contact Page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: contact_page.title_main
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title_main: prismic.KeyTextField;

	/**
	 * sub title field in *Contact Page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: contact_page.sub_title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	sub_title: prismic.KeyTextField;

	/**
	 * Slice Zone field in *Contact Page*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: contact_page.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<ContactPageDocumentDataSlicesSlice>;
}

/**
 * Contact Page document from Prismic
 *
 * - **API ID**: `contact_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ContactPageDocument<Lang extends string = string> =
	prismic.PrismicDocumentWithUID<
		Simplify<ContactPageDocumentData>,
		'contact_page',
		Lang
	>;

type PageDocumentDataSlicesSlice = StartScreenSlice;

/**
 * Content for Home documents
 */
interface PageDocumentData {
	/**
	 * Title field in *Home*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.TitleField;

	/**
	 * Slice Zone field in *Home*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
	 * Meta Title field in *Home*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: page.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */;
	meta_title: prismic.KeyTextField;

	/**
	 * Meta Description field in *Home*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: page.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	meta_description: prismic.KeyTextField;

	/**
	 * Meta Image field in *Home*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	meta_image: prismic.ImageField<never>;
}

/**
 * Home document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
	prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, 'page', Lang>;

type ServicesDocumentDataSlicesSlice = AllServicesSlice | StartScreenSlice;

/**
 * Content for Services documents
 */
interface ServicesDocumentData {
	/**
	 * Slice Zone field in *Services*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: services.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<ServicesDocumentDataSlicesSlice> /**
	 * Meta Title field in *Services*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: services.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */;
	meta_title: prismic.KeyTextField;

	/**
	 * Meta Description field in *Services*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: services.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	meta_description: prismic.KeyTextField;

	/**
	 * Meta Image field in *Services*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: services.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	meta_image: prismic.ImageField<never>;
}

/**
 * Services document from Prismic
 *
 * - **API ID**: `services`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ServicesDocument<Lang extends string = string> =
	prismic.PrismicDocumentWithUID<
		Simplify<ServicesDocumentData>,
		'services',
		Lang
	>;

export type AllDocumentTypes =
	| ContactPageDocument
	| PageDocument
	| ServicesDocument;

/**
 * Item in *ServiceItem → Default → Primary → Button Group*
 */
export interface AllServicesSliceDefaultPrimaryButtonGroupItem {
	/**
	 * Button Name field in *ServiceItem → Default → Primary → Button Group*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: all_services.default.primary.button_group[].button_name
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	button_name: prismic.KeyTextField;

	/**
	 * Button Link field in *ServiceItem → Default → Primary → Button Group*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: all_services.default.primary.button_group[].button_link
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	button_link: prismic.KeyTextField;
}

/**
 * Primary content in *ServiceItem → Default → Primary*
 */
export interface AllServicesSliceDefaultPrimary {
	/**
	 * title field in *ServiceItem → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: all_services.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField;

	/**
	 * Description field in *ServiceItem → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: all_services.default.primary.description
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	description: prismic.KeyTextField;

	/**
	 * image service field in *ServiceItem → Default → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: all_services.default.primary.image_service
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image_service: prismic.ImageField<never>;

	/**
	 * color field in *ServiceItem → Default → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: black
	 * - **API ID Path**: all_services.default.primary.color
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	color: prismic.SelectField<'black' | 'white', 'filled'>;

	/**
	 * Button Group field in *ServiceItem → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: all_services.default.primary.button_group[]
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	button_group: prismic.GroupField<
		Simplify<AllServicesSliceDefaultPrimaryButtonGroupItem>
	>;
}

/**
 * Default variation for ServiceItem Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AllServicesSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<AllServicesSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *ServiceItem*
 */
type AllServicesSliceVariation = AllServicesSliceDefault;

/**
 * ServiceItem Shared Slice
 *
 * - **API ID**: `all_services`
 * - **Description**: AllServices
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AllServicesSlice = prismic.SharedSlice<
	'all_services',
	AllServicesSliceVariation
>;

/**
 * Item in *ContactInfo → Default → Primary → items*
 */
export interface ContactInfoSliceDefaultPrimaryItemsItem {
	/**
	 * platform field in *ContactInfo → Default → Primary → items*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: telegram
	 * - **API ID Path**: contact_info.default.primary.items[].platform
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	platform: prismic.SelectField<
		'telegram' | 'whatsapp' | 'instagram',
		'filled'
	>;

	/**
	 * url field in *ContactInfo → Default → Primary → items*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: contact_info.default.primary.items[].url
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	url: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Primary content in *ContactInfo → Default → Primary*
 */
export interface ContactInfoSliceDefaultPrimary {
	/**
	 * address field in *ContactInfo → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: contact_info.default.primary.address
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	address: prismic.KeyTextField;

	/**
	 * phone field in *ContactInfo → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: contact_info.default.primary.phone
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	phone: prismic.KeyTextField;

	/**
	 * email field in *ContactInfo → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: contact_info.default.primary.email
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	email: prismic.KeyTextField;

	/**
	 * working hours field in *ContactInfo → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: contact_info.default.primary.working_hours
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	working_hours: prismic.RichTextField;

	/**
	 * items field in *ContactInfo → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: contact_info.default.primary.items[]
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	items: prismic.GroupField<Simplify<ContactInfoSliceDefaultPrimaryItemsItem>>;

	/**
	 * map embed url field in *ContactInfo → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: contact_info.default.primary.map_embed_url
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	map_embed_url: prismic.KeyTextField;
}

/**
 * Default variation for ContactInfo Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactInfoSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<ContactInfoSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *ContactInfo*
 */
type ContactInfoSliceVariation = ContactInfoSliceDefault;

/**
 * ContactInfo Shared Slice
 *
 * - **API ID**: `contact_info`
 * - **Description**: ContactInfo
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactInfoSlice = prismic.SharedSlice<
	'contact_info',
	ContactInfoSliceVariation
>;

/**
 * Primary content in *StartScreen → Default → Primary*
 */
export interface StartScreenSliceDefaultPrimary {
	/**
	 * Main title field in *StartScreen → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: start_screen.default.primary.main_title
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	main_title: prismic.KeyTextField;

	/**
	 * second text field in *StartScreen → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Second title
	 * - **API ID Path**: start_screen.default.primary.second_text
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	second_text: prismic.KeyTextField;

	/**
	 * Description  field in *StartScreen → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: start_screen.default.primary.description
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	description: prismic.KeyTextField;

	/**
	 * image_url field in *StartScreen → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: start_screen.default.primary.image_url
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	image_url: prismic.KeyTextField;
}

/**
 * Default variation for StartScreen Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type StartScreenSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<StartScreenSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *StartScreen*
 */
type StartScreenSliceVariation = StartScreenSliceDefault;

/**
 * StartScreen Shared Slice
 *
 * - **API ID**: `start_screen`
 * - **Description**: StartScreen
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type StartScreenSlice = prismic.SharedSlice<
	'start_screen',
	StartScreenSliceVariation
>;

declare module '@prismicio/client' {
	interface CreateClient {
		(
			repositoryNameOrEndpoint: string,
			options?: prismic.ClientConfig,
		): prismic.Client<AllDocumentTypes>;
	}

	interface CreateWriteClient {
		(
			repositoryNameOrEndpoint: string,
			options: prismic.WriteClientConfig,
		): prismic.WriteClient<AllDocumentTypes>;
	}

	interface CreateMigration {
		(): prismic.Migration<AllDocumentTypes>;
	}

	namespace Content {
		export type {
			ContactPageDocument,
			ContactPageDocumentData,
			ContactPageDocumentDataSlicesSlice,
			PageDocument,
			PageDocumentData,
			PageDocumentDataSlicesSlice,
			ServicesDocument,
			ServicesDocumentData,
			ServicesDocumentDataSlicesSlice,
			AllDocumentTypes,
			AllServicesSlice,
			AllServicesSliceDefaultPrimaryButtonGroupItem,
			AllServicesSliceDefaultPrimary,
			AllServicesSliceVariation,
			AllServicesSliceDefault,
			ContactInfoSlice,
			ContactInfoSliceDefaultPrimaryItemsItem,
			ContactInfoSliceDefaultPrimary,
			ContactInfoSliceVariation,
			ContactInfoSliceDefault,
			StartScreenSlice,
			StartScreenSliceDefaultPrimary,
			StartScreenSliceVariation,
			StartScreenSliceDefault,
		};
	}
}
